# Generated by Django 2.1.7 on 2019-03-24 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='imagefile',
            field=models.ImageField(default='/media/candidates/default.png', upload_to='candidates/'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datecreated',
            field=models.DateTimeField(default=datetime.date(2019, 3, 24), null=True),
        ),
    ]
