# Generated by Django 2.1.7 on 2019-03-29 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190324_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='datecreated',
            field=models.DateTimeField(default=datetime.date(2019, 3, 29), null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
