# Generated by Django 2.1.7 on 2019-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190329_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='imagefile',
            field=models.ImageField(upload_to='candidates'),
        ),
    ]
