# Generated by Django 2.1.7 on 2019-03-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20190329_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='imagefile',
            field=models.ImageField(default='default.png', upload_to='candidates'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
