# Generated by Django 2.1.7 on 2019-03-30 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20190329_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votelimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datecreated',
            field=models.DateTimeField(default=datetime.date(2019, 3, 30), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.TextField(choices=[('Active', 'A'), ('Inactive', 'I')], default='I'),
        ),
    ]
