# Generated by Django 2.1.7 on 2019-03-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.TextField(null=True),
        ),
    ]
